# Generated by Django 5.2 on 2025-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verifayed',
            field=models.BooleanField(default=False),
        ),
    ]
