# Generated by Django 5.1.6 on 2025-04-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verifayed',
            new_name='is_verified',
        ),
    ]
